### ISSUE TITLE
Respect OSS bundle best practices

### ISSUE THREAD

**Issue by vincentchalamon** [silverbackis/api-components-bundle#28]
- [x] Migrate configuration from YAML to XML
- [x] Create a route loader
- [x] Create a Symfony recipe on https://github.com/symfony/recipes-contrib
- [x] Replace DoctrineSubscriber and EntitySubscriber by [Doctrine EntityListeners](https://www.doctrine-project.org/projects/doctrine-bundle/en/latest/entity-listeners.html)
- [x] Remove useless travis.php.ini
- [x] Use `controler.service_arguments` tag on Action services
- [x] (optional) Use `@author` on each class or nowhere (configure php_cs.dist accordingly)

**Comment by silverbackdan** [comment]
- Yes to XML convert
- Route loader is OK
- Recipe: https://github.com/silverbackis/recipes-contrib/tree/api-component-bundle/silverback/api-component-bundle/2.0
- Doctrine are listeners in v2
- Well spotted for travis
- Will be good to double check `controler.service_arguments` tags in services config
- Yes please to reconfiguring php_cs.dist

**Comment by silverbackdan** [comment]
Recipe created but repository will not accept until there is a release tag `2.0` - can't seem to see a way around this so will re-submit when we have an alpha version tagged. Hopefully it'll allow it with that. All other OSS issues resolved, no yaml configs left. Doctrine migrated to xml too. (just have to remove the useless annotations).
